services:

  python:
    build:
      context: .
      target: python
      dockerfile: Dockerfile
    container_name: python
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    networks:
      - cmt-v2
      - curriculum-mapping-tool_sail
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000

  blackd:
    restart: always
    image: docker.io/pyfound/black
    command: blackd --bind-host 0.0.0.0 --bind-port 45484
    ports:
      - "45484:45484"

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3330:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - cmt-v2-mysql:/var/lib/mysql
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
    networks:
      - cmt-v2

  npm:
      container_name: npm
      image: node:20
      ports:
        - 3000:3000
      volumes:
          - .:/home/node/curriculum-mapping-tool
      working_dir: /home/node/curriculum-mapping-tool/app
      user: 'node'
      networks:
        - cmt-v2
#      tty: true
      command: npm run dev

networks:
  cmt-v2:
    driver: bridge
  #use own neo4j container later and remove this
  curriculum-mapping-tool_sail:
    external: true

volumes:
  cmt-v2-mysql:
    driver: local